#!/usr/bin/python3
import os
a = input("backup?(no/anykey)")
if a=="n":
    exit()
a = input("OSL name:")
b = input("git master url(https://***.***/***/***.git):")
print("waiting...it will take a few time...")
os.system("mount /opt/osl/" + a + ".img /opt/osl/tmp")
os.chdir("/opt/osl/tmp")
os.system("tar -zcvf ./* arch.tar.gz")
os.system("mkdir /opt/osl/backup")
os.chdir("/opt/osl/backup")
os.system("git init")
os.system("cp /opt/osl/tmp/arch.tar.gz ./")
os.system("rm -rf /opt/osl/tmp/arch.tar.gz")
os.system("umount /opt/osl/tmp")
os.system("tar -zcvf - arch.tar.gz | split -d -b 10M - arch.tar.gz.")
os.system("rm -rf arch.tar.gz")
os.system("git remote add origin " + b)
os.system("git push -f origin master")
os.chdir("../")
os.system("rm -rf backup")
print("OK!")
exit()
