import os
a = od.getcwd()
print("将/opt/osl/disk.img克隆到/opt/osl/arch/arch.tar.gz*")
print("请确保disk.img的空间足够")
print("正在克隆，这会耗费许多时间")
os.chdir("/opt/osl")
os.system("mount ./disk.img ./tmp/")
os.chdir("./tmp")
os.system("tar -zcvf arch.tar.gz ./*")
os.system("tar -zcf - arch.tar.gz | split -d -b - 10m arch.tar.gz.")
os.system("rm -rf arch.tar.gz")
print("打包完毕，正在将必要文件复制到/opt/osl/arch/")
os.system("mv arch.tar.gz* ../arch/")
os.system("cp " + a + "/../bin/install.py " + a + "/../bin/uninstall.py " + a + "/../bin/startpsl " + "/opt/osl/arch/")
print("复制完毕，可以把/opt/osl/arch/下的文件发给你的朋友啦！如果要安装，像正常安装OSL一样安装就可以啦！")